language: go

go:
  - 1.10
  - 1.11

install:
  - go get ./...
  - go get -u github.com/golang/lint/golint

script:
  - go test -v -race -cpu=1,2 -cover ./...
  - golint -set_exit_status ./...
  - bash .cover.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
