language: go

go:
  - 1.8
  - 1.9

install:
  - go get ./...
  - go get -u github.com/golang/lint/golint

script:
  - go test -cpu=1,2 -v -cover ./...
  - go test -race -v ./...
  - golint -set_exit_status ./...
